import fs from "node:fs"
import path from "node:path"
import os from "node:os"
import type { SchedulerHandle } from "./scheduler"

// Cross-process bridge so the AGENT (running inside the opencode server child
// process) can create/list/remove scheduled jobs that live in the gateway's
// scheduler — i.e. you can just ASK the bot "ping me every morning" and it
// schedules it, instead of typing /schedule yourself.
//
// Architecture: the agent calls a `cronjob` tool (installed into opencode's
// global tool dir). The tool writes a request file; the gateway watches the
// inbox, resolves which chat the requesting session belongs to, performs the
// scheduler op, and writes a response the tool reads back. This mirrors how
// Hermes exposes one `cronjob` action tool over its internal JSON scheduler.

const BASE = path.join(os.homedir(), ".config", "hollywood", "agent-cron")
const IN_DIR = path.join(BASE, "in")
const OUT_DIR = path.join(BASE, "out")
// opencode loads custom tools from tool/ under its global config dir (verified:
// Config directories() lists the global dir first), so this is visible to every
// session without touching the user's project repo.
const TOOL_FILE = path.join(os.homedir(), ".config", "opencode", "tool", "cronjob.ts")

interface CronRequest {
  id: string
  sessionID: string
  action: string
  schedule?: string
  prompt?: string
  job_id?: string
}

// The tool source written to disk. Uses ONLY node builtins so it resolves no
// matter which directory opencode imports it from.
const TOOL_SOURCE = `import fs from "node:fs"
import path from "node:path"
import os from "node:os"
import crypto from "node:crypto"

// Auto-generated by the Hollycode gateway. Lets the agent schedule recurring
// tasks that the gateway delivers back to the current chat.
const BASE = path.join(os.homedir(), ".config", "hollywood", "agent-cron")

export default {
  description:
    "Schedule the agent to run a task automatically on a cron schedule and deliver the result back to THIS chat. " +
    "Use when the user asks to be pinged/reminded/updated on a schedule, or wants a recurring 'heartbeat'. " +
    "action='create' needs schedule (cron) + prompt; action='list' shows this chat's jobs; action='remove' needs job_id. " +
    "Cron format is 'min hour day month weekday' (e.g. '0 9 * * *' = 9am daily, '*/10 * * * *' = every 10 minutes). " +
    "For a quiet heartbeat/watchdog that only messages when something is worth reporting, make the prompt instruct the agent to reply with exactly 'NOOP' when there is nothing to say — NOOP replies are not delivered. " +
    "Pass an empty string for fields that do not apply.",
  args: {
    action: { type: "string", enum: ["create", "list", "remove"], description: "create, list, or remove a scheduled job." },
    schedule: { type: "string", description: "Cron expression for create, e.g. '0 9 * * *'. Empty for list/remove." },
    prompt: { type: "string", description: "What to do on each run, in natural language. Empty for list/remove." },
    job_id: { type: "string", description: "Job id to remove (from action='list'). Empty for create/list." },
  },
  async execute(args: any, ctx: any) {
    const id = crypto.randomUUID()
    const inDir = path.join(BASE, "in")
    const outDir = path.join(BASE, "out")
    fs.mkdirSync(inDir, { recursive: true })
    fs.mkdirSync(outDir, { recursive: true })
    const req = {
      id,
      sessionID: ctx && ctx.sessionID ? ctx.sessionID : "",
      action: String(args.action || ""),
      schedule: String(args.schedule || ""),
      prompt: String(args.prompt || ""),
      job_id: String(args.job_id || ""),
    }
    fs.writeFileSync(path.join(inDir, id + ".json"), JSON.stringify(req))
    const outPath = path.join(outDir, id + ".json")
    for (let i = 0; i < 30; i++) {
      await new Promise((r) => setTimeout(r, 400))
      if (fs.existsSync(outPath)) {
        try {
          const res = JSON.parse(fs.readFileSync(outPath, "utf8"))
          try { fs.unlinkSync(outPath) } catch {}
          return (res.ok ? "OK: " : "Error: ") + res.message
        } catch {
          break
        }
      }
    }
    return "Scheduling request was queued (no confirmation yet). Use action='list' to verify."
  },
}
`

/** Install the `cronjob` agent tool into opencode's global tool dir. */
export function installAgentCronTool() {
  try {
    fs.mkdirSync(path.dirname(TOOL_FILE), { recursive: true })
    fs.mkdirSync(IN_DIR, { recursive: true })
    fs.mkdirSync(OUT_DIR, { recursive: true })
    if (!fs.existsSync(TOOL_FILE) || fs.readFileSync(TOOL_FILE, "utf8") !== TOOL_SOURCE) {
      fs.writeFileSync(TOOL_FILE, TOOL_SOURCE)
    }
  } catch {
    /* best-effort */
  }
}

/** Process pending agent cron requests (call on an interval). */
export function processAgentCronInbox(deps: {
  scheduler: SchedulerHandle | undefined
  chatForSession: (sid: string) => { channelId: string; conversationId: string } | undefined
  log: (scope: string, message: string) => void
}) {
  let files: string[]
  try {
    files = fs.readdirSync(IN_DIR).filter((f) => f.endsWith(".json"))
  } catch {
    return // inbox dir not created yet
  }
  for (const f of files) {
    const inPath = path.join(IN_DIR, f)
    let req: CronRequest
    try {
      req = JSON.parse(fs.readFileSync(inPath, "utf8")) as CronRequest
    } catch {
      try { fs.unlinkSync(inPath) } catch {}
      continue
    }
    const respond = (ok: boolean, message: string) => {
      try { fs.writeFileSync(path.join(OUT_DIR, req.id + ".json"), JSON.stringify({ ok, message })) } catch {}
      try { fs.unlinkSync(inPath) } catch {}
    }
    if (!deps.scheduler) { respond(false, "Scheduler is not available."); continue }
    const chat = deps.chatForSession(req.sessionID)
    if (!chat && req.action !== "list") { respond(false, "Could not resolve which chat to deliver to."); continue }
    try {
      if (req.action === "create") {
        if (!req.schedule || !req.prompt) { respond(false, "Both a schedule (cron) and a prompt are required."); continue }
        const job = deps.scheduler.add({
          cron: req.schedule,
          prompt: req.prompt,
          channelId: chat!.channelId,
          conversationId: chat!.conversationId,
        })
        deps.log("cron", `agent scheduled job ${job.id}: ${req.prompt.slice(0, 50)}`)
        respond(true, `Scheduled job ${job.id} — runs on "${req.schedule}". Remove with action="remove", job_id="${job.id}".`)
      } else if (req.action === "list") {
        const jobs = deps.scheduler
          .list()
          .filter((j) => !chat || (j.channelId === chat.channelId && j.conversationId === chat.conversationId))
        respond(true, jobs.length ? "Scheduled jobs:\n" + jobs.map((j) => `- ${j.id}: "${j.prompt}" (${j.cron})`).join("\n") : "No scheduled jobs.")
      } else if (req.action === "remove") {
        if (!req.job_id) { respond(false, "job_id is required to remove a job."); continue }
        const ok = deps.scheduler.remove(req.job_id)
        respond(ok, ok ? `Removed job ${req.job_id}.` : `No job with id ${req.job_id}.`)
      } else {
        respond(false, `Unknown action "${req.action}". Use create, list, or remove.`)
      }
    } catch (err: any) {
      respond(false, `Failed: ${err?.message ?? err}`)
    }
  }
}
